### ISSUE TITLE
Feature - Exclude projects

### ISSUE THREAD

**Issue by GoranHalvarsson** [ethisysltd/helix-check#4]
Great work guys
It would be nice to be able to exclude projects. 

For instance, if it's a Commerce project. I would like to exclude projects that are not following the naming convention, like the Sitecore.Commerce.ServiceProxy.csproj.

**Comment by GoranHalvarsson** [comment]
Any one reading this?

**Comment by ReoKzK** [comment]
Hi Goran, thanks for contacting and yes, we're reading this.

Currently that should work, if a project in solution doesn't follow Helix naming it won't be checked, did you try that?
I will add exclusions for specific projects in the next release.

Please let me know how you're getting on.

**Comment by GoranHalvarsson** [comment]
Hello
Yes, I hear you. I tried with a project not following the Helix naming. Unfortunately, it raised en error

**Comment by ReoKzK** [comment]
Okay Goran, I will add this feature quite soon, probably this week. Will give you a shout once it's live so you can test is with your project.

**Comment by GoranHalvarsson** [comment]
I also tried with a project, src\Environment\platform\myprojectName.Environment.csproj. Also did not ignore it. Which of course is good, but in this case I want it to be ignored :-)

**Comment by ReoKzK** [comment]
Hey Goran, new release v1.0.1 has been deployed.
New input param `excluded-projects` has been added, it can be used like this:

```
excluded-projects: 'Helixbase.Feature.NotFollowingHelix,Helixbase.Feature.AnotherNotFollowingHelix
```
Please check the readme and let me know if that works for you

**Comment by GoranHalvarsson** [comment]
Nicely done, will test at once :-)

**Comment by GoranHalvarsson** [comment]
Yes, it works great! thank you

**Comment by ReoKzK** [comment]
Awesome, thanks for checking Goran! I will close this issue.
